import PDFDocument from 'pdfkit';

export interface IReportOptions {
  title: string;
  reportType: string;
  department: string;
  author: string;
  summary: string;
  sections: Array<{ heading: string; body: string }>;
}

export const generatePDFReportStream = (options: IReportOptions): InstanceType<typeof PDFDocument> => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  // Header Banner
  doc
    .rect(0, 0, 595.28, 70)
    .fill('#0B0F17');

  doc
    .fillColor('#00F2FE')
    .fontSize(20)
    .font('Helvetica-Bold')
    .text('INDUSMIND AI', 40, 20);

  doc
    .fillColor('#94A3B8')
    .fontSize(10)
    .font('Helvetica')
    .text('Industrial Knowledge Intelligence Platform | ET AI Hackathon 2026', 40, 44);

  doc.moveDown(3);

  // Title Block
  doc
    .fillColor('#0F172A')
    .fontSize(18)
    .font('Helvetica-Bold')
    .text(options.title.toUpperCase(), 40, 95);

  doc
    .fontSize(9)
    .font('Helvetica')
    .fillColor('#64748B')
    .text(`Type: ${options.reportType}   |   Department: ${options.department}   |   Generated By: ${options.author}   |   Date: ${new Date().toLocaleDateString()}`, 40, 120);

  doc.lineCap('butt').moveTo(40, 135).lineTo(555, 135).strokeColor('#E2E8F0').lineWidth(1).stroke();

  // Summary Card
  doc
    .rect(40, 150, 515, 65)
    .fillAndStroke('#F8FAFC', '#CBD5E1');

  doc
    .fillColor('#1E293B')
    .fontSize(10)
    .font('Helvetica-Bold')
    .text('EXECUTIVE AI SUMMARY', 52, 160);

  doc
    .fillColor('#334155')
    .fontSize(9)
    .font('Helvetica')
    .text(options.summary, 52, 178, { width: 490 });

  let currentY = 235;

  // Sections
  options.sections.forEach(sec => {
    if (currentY > 700) {
      doc.addPage();
      currentY = 50;
    }

    doc
      .fillColor('#0284C7')
      .fontSize(12)
      .font('Helvetica-Bold')
      .text(sec.heading, 40, currentY);

    currentY += 18;

    doc
      .fillColor('#334155')
      .fontSize(9.5)
      .font('Helvetica')
      .text(sec.body, 40, currentY, { width: 515, align: 'left' });

    currentY += doc.heightOfString(sec.body, { width: 515 }) + 20;
  });

  // Footer
  const pageCount = doc.bufferedPageRange().count;
  for (let i = 0; i < pageCount; i++) {
    doc.switchToPage(i);
    doc
      .fontSize(8)
      .fillColor('#94A3B8')
      .text(
        `INDUSMIND AI Enterprise Confidential Report  |  Page ${i + 1} of ${pageCount}`,
        40,
        800,
        { align: 'center', width: 515 }
      );
  }

  doc.end();
  return doc;
};
